### ISSUE TITLE
Mount .NET Data Protection secrets in a Docker volume

### ISSUE THREAD

**Issue by Trivivium** [Trivivium/devops-2k20#101]
When the container is redeployed with a newer version it seems like the .NET Data Protection secrets are destroyed. We could move the root folder into a volume to avoid this.

https://sentry.io/organizations/minitwit/issues/1595238101/?query=is%3Aunresolved

**Comment by Trivivium** [comment]
@Akons97 You opened the issue again? What do we need to close this one?

**Comment by Akons97** [comment]
@Trivivium I still don't see the new volume we mounted?  Is it because docker swarm?

**Comment by Trivivium** [comment]
@Akons97 As I mentioned when we spoke I don't know as I don't know how Docker Swarm handles volumes. However, we should also talk about how critical this is now that the simulator has stopped. I think we should take note of this, and then spend the time discussing the consequences in the report. 

Feel free to the close the issue if you agree ;)
