### ISSUE TITLE
Figure out how the gravatar URL is computed and port it from python

### ISSUE THREAD

**Issue by Trivivium** [Trivivium/devops-2k20#11]
I have prepared the implementation of how the Gravatar URL is computed. We need someone with Python skills (read not me) to figure out what is currently happening and port it to C#.

The code should be located in: `src/WebApplication/ViewModels/Timeline/TimelineMessageVM.cs`

**Comment by C0DK** [comment]
it's a simple md5 hash of the email :) i'll implement it though.

**Comment by C0DK** [comment]
solved by https://github.com/Trivivium/devops-2k20/pull/21
