### ISSUE TITLE
 Service Level Agreements (SLAs)

### ISSUE THREAD

**Issue by andersbjergfelt** [Trivivium/devops-2k20#63]
Commitment between a service provider and a client.
Particular aspects of the service are agreed upon
quality
availability
responsibilities

Common metrics for web apps / services
Uptime/availability (usually percentage of all time)
Mean response time (average time before answer)
Mean time to recover (time to recover after outage)
Failure frequency (number of failures/timeouts over time)

**Comment by C0DK** [comment]
#66 WIP can be found here
