### ISSUE TITLE
Give us notifications when the production server throws errors

### ISSUE THREAD

**Issue by C0DK** [Trivivium/devops-2k20#78]
This could be easily fixed by using sentry.io for instance. But maybe it can be implemented via Grafana/Prometheus.

**Comment by C0DK** [comment]
@Trivivium @andersbjergfelt you guys probably know how easy we can get an email/trigger from/for Grafana.

**Comment by andersbjergfelt** [comment]
How easy is it to setup sentry.io? Else I can look into triggers

**Comment by C0DK** [comment]
1) create account
2) add 3 lines of code
3) success
Then i'll get an email but i can just proxy them to the chat manually
