### ISSUE TITLE
Fix: An error occurred using the connection to database 'MiniTwit' on server 'db'.

### ISSUE THREAD

**Issue by C0DK** [Trivivium/devops-2k20#92]
https://sentry.io/organizations/minitwit/issues/1604630429/?project=5187188&query=is%3Aunresolved

**Comment by C0DK** [comment]
I think this happens because the request is canceled somewhere else maybe? and this then get's cancelled which raises an error because cancelation isn't handled? maybe?

**Comment by C0DK** [comment]
however the error is raised in `set latest`. however i cannot replicate it with cURL

**Comment by C0DK** [comment]
We should check if this is fixed.

**Comment by andersbjergfelt** [comment]
I guess this is fixed with the merged #99 ??
